# Generated by Django 5.2 on 2025-05-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['region', 'rank']},
        ),
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
