# Generated by Django 5.2 on 2025-05-05 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_matchup_away_team_matchup_home_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='away_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchup',
            name='home_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchup',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='match_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
