# Generated by Django 5.2 on 2025-05-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_matchup_away_score_matchup_home_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
