# Generated by Django 5.2 on 2025-05-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_matchup_away_from_match_matchup_away_from_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
