# Generated by Django 5.2 on 2025-11-25 02:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_tournamentround_matchup_tournament_round_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['region', 'name']},
        ),
        migrations.RemoveField(
            model_name='team',
            name='rank',
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('start_time', models.DateTimeField()),
                ('home_source_take_winner', models.BooleanField(blank=True, null=True)),
                ('away_source_take_winner', models.BooleanField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('away_source_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_for_match', to='matches.match')),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='matches.team')),
                ('home_source_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_for_match', to='matches.match')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='matches.team')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.room')),
                ('tournament_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.tournamentround')),
            ],
        ),
        migrations.DeleteModel(
            name='Matchup',
        ),
    ]
