# Generated by Django 5.2 on 2025-11-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_alter_team_options_remove_team_rank_match_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
        migrations.AddField(
            model_name='team',
            name='emoji',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
