# Generated by Django 5.2 on 2025-11-25 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_alter_match_options_team_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='match',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.room'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.tournamentround'),
        ),
        migrations.AlterField(
            model_name='team',
            name='emoji',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.region'),
        ),
        migrations.AddField(
            model_name='match',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.timeslot'),
        ),
    ]
