# Generated by Django 5.2 on 2026-01-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_tournamentbracket_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentround',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='tournamentround',
            constraint=models.UniqueConstraint(fields=('bracket', 'name'), name='unique_bracket_and_round_name'),
        ),
    ]
